course/course/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls', namespace='info')),
]

course/info/urls.py
from django.urls import path

import info.views as iv

app_name = 'info'
app_name = 'forum'
urlpatterns = [
    path('export-clients-xlsx/', iv.get_characters_xlsx, name='characters_xlsx'),
    path('export-items-xlsx/', iv.get_items_xlsx, name='items_xlsx'),
    path('export-locations-xlsx/', iv.get_locations_xlsx, name='locations_xlsx'),
    path('export-quests-xlsx/', iv.get_quests_xlsx, name='quests_xlsx'),
    path('export-spells-xlsx/', iv.get_spells_xlsx, name='spells_xlsx'),

    path('register/', iv.RegisterUser.as_view(), name='register'),
    path('login/', iv.LoginUser.as_view(), name='login'),
    path('logout/', iv.logout_user, name='logout'),
    path('', iv.home, name='home'),
    path('characters/', iv.characters, name='characters'),
    path('character/<slug:slug>', iv.character_detail, name='character_detail'),
    path('spells/', iv.spells, name='spells'),
    path('spell/<slug:slug>', iv.spell_detail, name='spell_detail'),
    path('locations/', iv.locations, name='locations'),
    path('location/<slug:slug>', iv.location_detail, name='location_detail'),
    path('items/', iv.items, name='items'),
    path('item/<slug:slug>', iv.item_detail, name='item_detail'),
    path('quests/', iv.quests, name='quests'),
    path('quest/<slug:slug>', iv.quest_detail, name='quest_detail'),
]

course/info/models.py
from django.db import models
from django.urls import reverse
from django.contrib.postgres.fields import IntegerRangeField

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _



class Entries(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    content = models.TextField(blank=True)

    def __str__(self):
        return self.title

class Characters(models.Model):
    entry = models.OneToOneField(Entries, primary_key=True, on_delete=models.CASCADE)
    strength = models.PositiveSmallIntegerField()
    will = models.PositiveSmallIntegerField()
    influence = models.PositiveIntegerField()
    observation = models.PositiveIntegerField()
    lore = models.PositiveIntegerField()
    CHOICES = (
        ('Hybrid', 'Hybrid'),
        ('Human', 'Human'),
    )
    loyalty = models.CharField(max_length=300, choices = CHOICES)

    # loyalty = models.BooleanField()
    # if models.BooleanField() :
    #     is_friendly = "Human"
    # else:
    #     is_friendly = "Hybrid"


    def __str__(self):
        return self.entry.__str__()
    
    def get_absolute_url(self):
        return reverse('info:character_detail', kwargs={'slug': self.entry.slug})

class Spells(models.Model):
    entry = models.OneToOneField(Entries, primary_key=True, on_delete=models.CASCADE)
    effect = models.TextField()

    def __str__(self):
        return self.entry.__str__()

    def get_absolute_url(self):
        return reverse('info:spell_detail', kwargs={'slug': self.entry.slug})

class Locations(models.Model):
    entry = models.OneToOneField(Entries, primary_key=True, on_delete=models.CASCADE)
    number = models.PositiveIntegerField()
    effect = models.TextField()

    def __str__(self):
        return self.entry.__str__()

    def get_absolute_url(self):
        return reverse('info:location_detail', kwargs={'slug': self.entry.slug})

class Items(models.Model):
    entry = models.OneToOneField(Entries, primary_key=True, on_delete=models.CASCADE)
    effect = models.TextField()

    def __str__(self):
        return self.entry.__str__()

    def get_absolute_url(self):
        return reverse('info:item_detail', kwargs={'slug': self.entry.slug})

class Quests(models.Model):
    entry = models.OneToOneField(Entries, primary_key=True, on_delete=models.CASCADE)
    crisis = models.TextField()
    target_number = models.PositiveIntegerField()
    items = models.ManyToManyField(Items, blank=True)

    def __str__(self):
        return self.entry.__str__()

    def get_absolute_url(self):
        return reverse('info:quest_detail', kwargs={'slug': self.entry.slug})




class ForumUsers(models.Model):
    user = models.OneToOneField(User, verbose_name=_('user'), related_name='forumusers', on_delete=models.CASCADE)
    read_only = models.BooleanField(verbose_name=_('read_only'))

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_forum_user(sender, instance, created, **kwargs):
    if created:
        ForumUsers.objects.create(user=instance, read_only=False)

@receiver(post_save, sender=User)
def save_forum_user(sender, instance, **kwargs):
    instance.forumusers.save()

# class Comments(models.Model):
#     entry = models.ForeignKey(models.Entries, verbose_name=_('entry'), on_delete=models.CASCADE)
#     user = models.ForeignKey(ForumUsers, verbose_name=_('user'), on_delete=models.CASCADE)
#     publication_date = models.DateTimeField(verbose_name=_('publication_date'), auto_now_add=True)
#     content = models.TextField(verbose_name=_('content'))

course/info/views.py
from django.shortcuts import get_object_or_404, render
from .filters import *
from .models import *

import io
import xlsxwriter
from django.http import HttpResponse

import sender as sender
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.paginator import Paginator
from django.core.serializers import serialize
from django.db.models import Model
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View



from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User



def get_xlsx(request, model, columns, ws_name):
    output = io.BytesIO()

    filename = f'current-report.xlsx'
    workbook = xlsxwriter.Workbook(output, {'in_memory': True, 'default_date_format': 'dd/mm/yy',
                                            'time_format': 'hh:mm:ss'})
    worksheet = workbook.add_worksheet(ws_name)

    row_num = 0
    for col_num in range(len(columns)):
        worksheet.write(row_num, col_num, columns[col_num])

    print(field for field in columns)
    rows = model.objects.all().order_by(columns[0]).values_list(*columns)

    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            worksheet.write(row_num, col_num, row[col_num])

    workbook.close()
    output.seek(0)

    response = HttpResponse(output.read(),
                            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = f'attachment; filename={filename}'

    output.close()

    return response



def get_characters_xlsx(request):
    columns = ['entry', 'strength', 'will', 'influence', 'observation', 'lore', 'loyalty']
    return get_xlsx(request, Characters, columns, ws_name='Персонажи')

def get_items_xlsx(request):
    columns = ['entry', 'effect']
    return get_xlsx(request, Items, columns, ws_name='Карты предметов')

def get_spells_xlsx(request):
    columns = ['entry', 'effect']
    return get_xlsx(request, Spells, columns, ws_name='Карты заклинаний')

def get_quests_xlsx(request):
    columns = ['entry', 'crisis', 'target_number', 'items']
    return get_xlsx(request, Quests, columns, ws_name='Карты мифов')

def get_locations_xlsx(request):
    columns = ['entry', 'number', 'effect']
    return get_xlsx(request, Locations, columns, ws_name='Локации')




def home(request):
    return render(request, 'info/home.html')

def characters(request):
    characters = Characters.objects.all()

    myFilter = CharactersFilter(request.GET, queryset=characters)
    characters = myFilter.qs

    context = {'myFilter': myFilter, 'characters': characters, 'title': 'Персонажи - UnfathomableDB'}
    return render(request, 'info/characters.html', context)

def character_detail(request, slug):
    entry = get_object_or_404(Entries, slug=slug)
    character = get_object_or_404(Characters, entry=entry)
    context = {
        'character': character,
    }
    return render(request, 'info/character_detail.html', context)

def spells(request):
    spells = Spells.objects.all()

    myFilter = SpellsFilter(request.GET, queryset=spells)
    spells = myFilter.qs

    context = {'myFilter': myFilter, 'spells': spells, 'title': 'Карты заклинаний - UnfathomableDB'}
    return render(request, 'info/spells.html', context)

def spell_detail(request, slug):
    entry = get_object_or_404(Entries, slug=slug)
    spell = get_object_or_404(Spells, entry=entry)
    context = {
        'spell': spell,
    }
    return render(request, 'info/spell_detail.html', context)

def locations(request):
    locations = Locations.objects.all()

    myFilter = LocationsFilter(request.GET, queryset=locations)
    locations = myFilter.qs

    context = {'myFilter': myFilter, 'locations': locations, 'title': 'Локации корабля - UnfathomableDB'}
    return render(request, 'info/locations.html', context)

def location_detail(request, slug):
    entry = get_object_or_404(Entries, slug=slug)
    location = get_object_or_404(Locations, entry=entry)
    context = {
        'location': location,
    }
    return render(request, 'info/location_detail.html', context)

def items(request):
    items = Items.objects.all()

    myFilter = ItemsFilter(request.GET, queryset=items)
    items = myFilter.qs

    context = {'myFilter': myFilter, 'items': items, 'title': 'Карты предметов - UnfathomableDB'}
    return render(request, 'info/items.html', context)

def item_detail(request, slug):
    entry = get_object_or_404(Entries, slug=slug)
    item = get_object_or_404(Items, entry=entry)
    context = {
        'item': item,
    }
    return render(request, 'info/item_detail.html', context)

def quests(request):
    quests = Quests.objects.all()

    myFilter = QuestsFilter(request.GET, queryset=quests)
    quests = myFilter.qs

    context = {'myFilter': myFilter, 'quests': quests, 'title': 'Карты мифов - UnfathomableDB'}
    return render(request, 'info/quests.html', context)

def quest_detail(request, slug):
    entry = get_object_or_404(Entries, slug=slug)
    quest = get_object_or_404(Quests, entry=entry)
    context = {
        'quest': quest,
    }
    return render(request, 'info/quest_detail.html', context)


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'forum/register.html'
    success_url = reverse_lazy('forum:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация - UnfathomableDB'
        return context

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('info:home')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'forum/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Вход - UnfathomableDB'
        return context


def logout_user(request):
    logout(request)
    return redirect('forum:login')

course/info/templates/info/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'info/css/bootstrap.min.css' %}" rel="stylesheet">
    <title>{{ title }}</title>
</head>

<body>
    <script src="{% static 'info/js/bootstrap.bundle.min.js' %}"></script>

    <nav class="navbar navbar-dark bg-dark sticky-top">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-start text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
                aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Меню</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'info:items' %}">Карты предметов</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'info:characters' %}">Персонажи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'info:locations' %}">Локации корабля</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'info:quests' %}">Карты мифов</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'info:spells' %}">Карты заклинаний</a>
                        </li>
                    </ul>

                </div>

            </div>
            <a class="navbar-brand" href="{% url 'info:home' %}">UnfathomableDB</a>

            <div class="container-right">

                {% if request.user.is_authenticated %}
                <h5 style="display: inline;" class="text-light mx-3">{{ user.username }}</h5>
                <a style="display: inline;" class="btn btn-secondary" href="{% url 'forum:logout' %}" role="button">Выйти</a>
                {% else %}
                <a style="display: inline;" class="btn btn-primary mx-2" href="{% url 'forum:login' %}" role="button">Войти</a>
                <a style="display: inline;" class="btn btn-secondary" href="{% url 'forum:register' %}" role="button">Регистрация</a>
                {% endif %}
            </div>


        </div>
    </nav>

    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
</body>

</html>

course/info/templates/info/character_detail.html
{% extends 'info/base.html' %}

{% block content %}

<br>
<div class="card card-body">
    <div class="row">
        <div class="col border-bottom">
            <h1>{{ character.entry.title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col border-bottom">
            <br>
            Strength: {{ character.strength }}
            <br>
            Will: {{ character.will }}
            <br>
            Influence: {{ character.influence }}
            <br>
            Observation: {{ character.observation }}
            <br>
            Lore: {{ character.lore }}
            <br>
            Loyalty: {{ character.loyalty }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <br>
            <div class="container">
                {{ character.entry.content }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

course/info/templates/info/characters.html
{% extends 'info/entry_table.html' %}

{% block table_content %}

<thead>
<tr>
    <th>Title</th>
    <th>Strength</th>
    <th>Will</th>
    <th>Influence</th>
    <th>Observation</th>
    <th>Lore</th>
    <th>Loyalty</th>
</tr>
</thead>

<tbody>
{% for character in characters %}
<tr>
    <td style="position: relative;">
        <a href="{{ character.get_absolute_url }}" class="stretched-link"></a>{{character.entry}}
    </td>
    <td style="position: relative;">
        <a href="{{ character.get_absolute_url }}" class="stretched-link"></a>{{character.strength}}
    </td>
    <td style="position: relative;">
        <a href="{{ character.get_absolute_url }}" class="stretched-link"></a>{{character.will}}
    </td>
    <td style="position: relative;">
        <a href="{{ character.get_absolute_url }}" class="stretched-link"></a>{{character.influence}}
    </td>
    <td style="position: relative;">
        <a href="{{ character.get_absolute_url }}" class="stretched-link"></a>{{character.observation}}
    </td>
   <td style="position: relative;">
        <a href="{{ character.get_absolute_url }}" class="stretched-link"></a>{{character.lore}}
    </td>
    <td style="position: relative;">
        <a href="{{ character.get_absolute_url }}" class="stretched-link"></a>{{character.loyalty}}
    </td>
</tr>
{% endfor %}



    <a href="{% url 'info:characters_xlsx' %}" type="button" class="btn btn-light mt-4 mb-4">Выгрузить в xlsx</a>
</tbody>

{% endblock %}

course/info/templates/info/entry_table.html
{% extends 'info/base.html' %}

{% block content %}

<br>
<div class="row">
    <div class="col">
        <div class="card card-body">
            <form method="get">
                {{myFilter.form}}
                <button class="btn btn-primary" type="submit">
                    Искать
                </button>
            </form>
        </div>
    </div>
</div>

<br>
<div class="row">
    <div class="col">
        <div class="card card-body">
            <table class="table table-sm table-hover">
                {% block table_content %}
                {% endblock %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

course/info/templates/info/home.html
{% extends 'info/base.html' %}

{% block content %}
<p>БАЗА ДАННЫХ ПО НАСТОЛЬНОЙ ИГРЕ "НЕПОСТИЖИМОЕ"</p>
<div style="height: 50px;"></div>
<p>Здесь хранится информация о персонажах, их предметах, локациях корабля и тд.
    Вы можете как посмотреть все карты, так и найти нужные для вас
</p>
{% endblock %}

course/info/templates/info/item_detail.html
{% extends 'info/base.html' %}

{% block content %}

<br>
<div class="card card-body">
    <div class="row">
        <div class="col border-bottom">
            <h1>{{ item.entry.title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col border-bottom">
            <br>
            Effect: {{ item.effect }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <br>
            <div class="container">
                {{ item.entry.content }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

course/info/templates/info/items.html
{% extends 'info/entry_table.html' %}

{% block table_content %}

<thead>
<tr>
    <th>Title</th>
    <th>Effect</th>
</tr>
</thead>

<tbody>
    {% for item in items %}
    <tr>
        <td style="position: relative;">
            <a href="{{ item.get_absolute_url }}" class="stretched-link"></a>{{item.entry}}
        </td>
        <td style="position: relative;">
            <a href="{{ item.get_absolute_url }}" class="stretched-link"></a>{{item.effect}}
        </td>
    </tr>
    {% endfor %}

    <a href="{% url 'info:items_xlsx' %}" type="button" class="btn btn-light mt-4 mb-4">Выгрузить в xlsx</a>

</tbody>

{% endblock %}

course/info/templates/info/location_detail.html
{% extends 'info/base.html' %}

{% block content %}

<br>
<div class="card card-body">
    <div class="row">
        <div class="col border-bottom">
            <h1>{{ location.entry.title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col border-bottom">
            <br>
            Location number: {{ location.number }}
        </div>
    </div>
    <div class="row">
        <div class="col border-bottom">
            <br>
            Location effect: {{ location.effect }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <br>
            <div class="container">
                {{ location.entry.content }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

course/info/templates/info/locations.html
{% extends 'info/entry_table.html' %}

{% block table_content %}

<thead>
<tr>
    <th>Title</th>
    <th>Number</th>
    <th>Effect</th>
</tr>
</thead>

<tbody>
    {% for location in locations %}
    <tr>
        <td style="position: relative;">
            <a href="{{ location.get_absolute_url }}" class="stretched-link"></a>{{location.entry}}
        </td>
        <td style="position: relative;">
            <a href="{{ location.get_absolute_url }}" class="stretched-link"></a>{{location.number}}
        </td>
        <td style="position: relative;">
            <a href="{{ location.get_absolute_url }}" class="stretched-link"></a>{{location.effect}}
        </td>
    </tr>
    {% endfor %}

    <a href="{% url 'info:locations_xlsx' %}" type="button" class="btn btn-light mt-4 mb-4">Выгрузить в xlsx</a>


</tbody>

{% endblock %}

course/info/templates/info/quest_detail.html
{% extends 'info/base.html' %}

{% block content %}

<br>
<div class="card card-body">
    <div class="row">
        <div class="col border-bottom">
            <h1>{{ quest.entry.title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col border-bottom">
            <br>
            Crisis: {{ quest.crisis }}
            <br>
            Target number: {{ quest.target_number }}
            <br>
            Reward items: {{ quest.items }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <br>
            <div class="container">
                {{ quest.entry.content }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

course/info/templates/info/quests.html
{% extends 'info/entry_table.html' %}

{% block table_content %}

<thead>
<tr>
    <th>Title</th>
    <th>Crisis</th>
    <th>Target number</th>
    <th>Items</th>
</tr>
</thead>

<tbody>
    {% for quest in quests %}
    <tr>
        <td style="position: relative;">
            <a href="{{ quest.get_absolute_url }}" class="stretched-link"></a>{{quest.entry}}
        </td>
        <td style="position: relative;">
            <a href="{{ spell.get_absolute_url }}" class="stretched-link"></a>{{quest.crisis}}
        </td>
        <td style="position: relative;">
            <a href="{{ quest.get_absolute_url }}" class="stretched-link"></a>{{quest.target_number}}
        </td>
        <td style="position: relative;">
            <a href="{{ quest.get_absolute_url }}" class="stretched-link"></a>{{quest.items}}
        </td>
    </tr>
    {% endfor %}

    <a href="{% url 'info:quests_xlsx' %}" type="button" class="btn btn-light mt-4 mb-4">Выгрузить в xlsx</a>

</tbody>

{% endblock %}

course/info/templates/info/spell_detail.html
{% extends 'info/base.html' %}

{% block content %}

<br>
<div class="card card-body">
    <div class="row">
        <div class="col border-bottom">
            <h1>{{ spell.entry.title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col border-bottom">
            <br>
            Cost: {{ spell.effect }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <br>
            <div class="container">
                {{ spell.entry.content }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

course/info/templates/info/spells.html
{% extends 'info/entry_table.html' %}

{% block table_content %}

<thead>
<tr>
    <th>Title</th>
    <th>Effect</th>
</tr>
</thead>

<tbody>
    {% for spell in spells %}
    <tr>
        <td style="position: relative;">
            <a href="{{ spell.get_absolute_url }}" class="stretched-link"></a>{{spell.entry}}
        </td>
        <td style="position: relative;">
            <a href="{{ spell.get_absolute_url }}" class="stretched-link"></a>{{spell.effect}}
        </td>
    </tr>
    {% endfor %}

    <a href="{% url 'info:spells_xlsx' %}" type="button" class="btn btn-light mt-4 mb-4">Выгрузить в xlsx</a>

    </tbody>

{% endblock %}